# Generated by Django 4.1.2 on 2023-01-17 20:07

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prestadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nome', models.CharField(max_length=90)),
                ('cpf', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('telefone', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=70)),
                ('nascimento', models.CharField(max_length=16)),
                ('senha', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=30)),
                ('cidade', models.CharField(max_length=30)),
                ('bairro', models.CharField(max_length=30)),
                ('rua', models.CharField(max_length=50)),
                ('numero', models.IntegerField(max_length=8)),
                ('complemento', models.CharField(max_length=30)),
                ('cep', models.CharField(max_length=15)),
                ('morador_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('morador_prestador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prestadores.prestador')),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
    ]
