# Generated by Django 4.1.2 on 2023-02-22 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_endereco_numero'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='endereco',
            managers=[
            ],
        ),
    ]
