# Generated by Django 4.1.2 on 2023-05-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_cliente_email_alter_endereco_complemento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=70),
        ),
    ]
