# Generated by Django 4.2.4 on 2023-09-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_cliente_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='foto',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
