# Generated by Django 4.2.4 on 2023-09-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_cliente_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='foto',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
    ]
