# Generated by Django 4.1.2 on 2023-01-17 20:07

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('prestadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=150)),
                ('detalhes', models.CharField(max_length=255)),
                ('data', models.CharField(max_length=16)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('preco_max', models.DecimalField(decimal_places=2, max_digits=8)),
                ('preco_min', models.DecimalField(decimal_places=2, max_digits=8)),
                ('clienteCPF', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('prestadroCPF', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prestadores.prestador')),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
    ]
