# Generated by Django 4.2.4 on 2023-09-19 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('prestadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=150)),
                ('detalhes', models.CharField(max_length=255)),
                ('data', models.CharField(max_length=16)),
                ('update', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('status', models.DecimalField(decimal_places=0, max_digits=2)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('preco_max', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('preco_min', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('clienteCPF', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('prestadorCPF', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prestadores.prestador')),
            ],
        ),
    ]
