# Generated by Django 4.1.2 on 2023-02-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
