# Generated by Django 4.1.2 on 2023-02-22 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0003_alter_prestador_managers'),
        ('demandas', '0002_alter_demanda_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='prestadroCPF',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='prestadores.prestador'),
            preserve_default=False,
        ),
    ]
