# Generated by Django 4.1.2 on 2023-02-22 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0003_alter_prestador_managers'),
        ('demandas', '0003_alter_demanda_prestadrocpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='prestadroCPF',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prestadores.prestador'),
        ),
    ]
