# Generated by Django 4.1.2 on 2023-03-26 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0004_alter_demanda_preco_alter_demanda_prestadrocpf'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='demanda',
            managers=[
            ],
        ),
    ]
