# Generated by Django 4.1.2 on 2023-03-26 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0005_alter_demanda_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demanda',
            name='preco_max',
        ),
    ]
