# Generated by Django 4.1.2 on 2023-03-26 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0006_remove_demanda_preco_max'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demanda',
            name='preco_min',
        ),
    ]
