# Generated by Django 4.1.2 on 2023-03-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0007_remove_demanda_preco_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='preco_max',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demanda',
            name='preco_min',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8),
            preserve_default=False,
        ),
    ]
