# Generated by Django 4.1.2 on 2023-03-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0008_demanda_preco_max_demanda_preco_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='preco_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='preco_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
