# Generated by Django 4.1.2 on 2023-05-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0009_alter_demanda_preco_max_alter_demanda_preco_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='update',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='preco_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='preco_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
    ]
