# Generated by Django 4.2.4 on 2023-09-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0011_rename_prestadrocpf_demanda_prestadorcpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='status',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True),
        ),
    ]
