# Generated by Django 4.2.4 on 2023-09-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0012_demanda_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='status',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
            preserve_default=False,
        ),
    ]
