# Generated by Django 4.2.4 on 2023-09-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('nome', models.CharField(max_length=90)),
                ('cpf', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('telefone', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=70)),
                ('nascimento', models.CharField(max_length=16)),
                ('senha', models.CharField(max_length=25)),
                ('especialidade', models.CharField(max_length=30)),
            ],
        ),
    ]
