# Generated by Django 4.1.2 on 2023-01-17 20:07

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('nome', models.CharField(max_length=90)),
                ('cpf', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('telefone', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=70)),
                ('nascimento', models.CharField(max_length=16)),
                ('senha', models.CharField(max_length=25)),
                ('especialidade', models.CharField(max_length=30)),
                ('cadastroValidade', models.BooleanField()),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
    ]
