# Generated by Django 4.1.2 on 2023-02-03 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestador',
            old_name='cadastroValidade',
            new_name='cadastroValidado',
        ),
    ]
