# Generated by Django 4.1.2 on 2023-02-22 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0002_rename_cadastrovalidade_prestador_cadastrovalidado'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='prestador',
            managers=[
            ],
        ),
    ]
