# Generated by Django 4.1.2 on 2023-05-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0004_alter_prestador_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestador',
            name='email',
            field=models.EmailField(max_length=70),
        ),
    ]
