# Generated by Django 4.2.4 on 2023-09-12 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0005_alter_prestador_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestador',
            name='cadastroValidado',
        ),
    ]
