# Generated by Django 4.2.4 on 2023-09-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0006_remove_prestador_cadastrovalidado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=90)),
            ],
        ),
    ]
